version: '3'

services:
  licences:
    build: .
    restart: unless-stopped
    hostname: matlab-license-manager
    mac_address: 54:bf:64:55:de:bc
    ports:
      - "27000:27000"
      - "27001:27001"