version: '3'

services:
  license_manager:
    build: .
    restart: unless-stopped
    hostname: matlab-license-manager
    mac_address: 54:bf:64:55:de:bc
    environment:
      - LMGRD_PORT=27000
      - MLM_PORT=27001
    ports:
      - "27000:27000"
      - "27001:27001"